name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Racket environment
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        version: 8.11.1
    - name: Check files
      run: test -e run-tests.rkt && echo "Test file exists" >> $GITHUB_STEP_SUMMARY || echo "Test file does not exist" >> $GITHUB_STEP_SUMMARY
    - name: Run check
      run: racket run-tests.rkt | grep -q '0 failure(s) 0 error(s)' && echo "All tests passed successfully." >> $GITHUB_STEP_SUMMARY || echo "Some tests failed." >> $GITHUB_STEP_SUMMARY
