name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Setup Racket environment
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        version: 8.11.1

    - name: Check files
      run: ls
      
    - name: Run check
      run: racket run-tests.rkt
