name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Racket environment
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        version: 8.11.1

    - name: Check files
      run: |
        if test -e run-tests.rkt; then 
          echo "Test file exists" >> $GITHUB_STEP_SUMMARY
        else 
          echo "Test file does not exist" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

    - name: Compile runtime.c
      run: gcc -c -g -std=c99 runtime.c
    - name: Run check
      run: |
        yes 10 | racket run-tests.rkt | tee /dev/tty | grep -q '0 failure(s) 0 error(s)'
        if [ $? -ne 0 ]; then
          echo "Some tests failed." >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "All tests passed successfully." >> $GITHUB_STEP_SUMMARY
        fi
